### ISSUE TITLE
Naming of org.knime.knip.scijava.commands

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip-scijava#1]
@Squareys 

see https://github.com/knime-ip/knip/issues/83.

We should eventually find another name for the project / packages when we better understand what will live in this package. At latest, this should happen before we start deploying dependent code to the end-user.

**Comment by Squareys** [comment]
This package provides:
- scijava Services which expose KNIME resources (such as input tables, output tables) to scijava. 
- adapters to convert KNIME types (such as Cells and DataValues) to types used by module items.
- Pre- and PostProcessors to build module input from DataTables and DataTables from module output. 
  [i]Summarized:[/i] A KNIME ScijavaContext (intended left out space. Commands require a Context to run, which contains Services, Commands (Ops etc)) to run Scijava Commands.

Later on this package will also provide some kind of UI Service which will harvest NodeDialogs/SettingsModels (There is an preliminary implementation already) and some classes (non-services) to build NodeDialogs from modules.

The scijava bridge (or whatever you want to call it) tries to make scijava commands work well in an knime environment without making additional changes to the command code necessary.

Later knip-scijava will also provide Nodes for loading command .class files (whereas knip-scripting provides nodes to actually develop scijava commands in different languages). Extension Points will make "wrapping scijava commands as knime nodes" possible for community developers. Since imagej2 plugins are scijava commands (if I understood correctly), knip-imagej2 will use exactly those extension points.

I hope this clears up a few things, we could create a Wiki-Page for the requirements of this repository.

**Comment by dietzc** [comment]
@Squareys thank you! Thats great! Later we should put this into the README.md of this project.

**Comment by Squareys** [comment]
I created a wiki-page: https://github.com/knime-ip/knip-scijava/wiki/knip-scijava
Feel free to edit/append/remove.

**Comment by gab1one** [comment]
Has been named org.knime.scijava.*.
