### ISSUE TITLE
Use OpMatchingService to Match Values to Parameters and Parameters to Cells

### ISSUE THREAD

**Issue by dietzc** [knime-ip/knip-scijava#15]
- [ ] Requires `ScijavaMatchingService` instead of `OpMatchingService`
- [ ] Reimplementation of  `InputAdapters` and `OutputAdapters`

**Comment by Squareys** [comment]
Is this still applicable to the way we handle conversions now?

**Comment by dietzc** [comment]
I'm actually not really sure.  Do the following use-case swork?
1. Use-Case Input: 
   Input: `Cell` of type `A`. 
   `ModuleInfo` requires primitive of type `B`.
   `Converter` exists from `A` `->` `B`.
2. Use-Case Output: 
   Output of `ModuleInfo` is `C`
   `CellFactory` extists for some `D` and there exists a  `Converter` from `C` to `D`.

Maybe we have to sneak the `SciJava` `Converter`s in (if they not already are...). I'm sure we don't need the `OpMatchingService` directly.

**Comment by Squareys** [comment]
Alright, just to make sure I undestand correctly:

> 1. Use-Case Input: 
>    Input: Cell of **DataType** A. 
>    ModuleInfo requires **Java Type** (not primitive) of type B.
>    **KNIME** Converter exists from **DataType A** -> B.
> 2. Use-Case Output: 
>    Output of ModuleInfo is **JavaType** C
>    **KNIME Converter** exists from C to some **DataType** D

Is that equivalent to what you wrote?

> Maybe we have to sneak the SciJava Converters in (if they not already are...).

Yes, we should, and no, they aren't. KNIME Converter Framework only provides lossless conversions. Hence, there is no Converter to `Byte`, since there is no `ByteCell`, which provides sufficiently bad integer range (long and int would both lose "percision" during conversion). Same for `Short` and `Char`. We could append Scijava converters from the preferred value type of the cell in case no direct conversion is possible.

**Comment by dietzc** [comment]
I think in SciJava also only loss-less `Converter`s are supported. So this shouldn't be a problem at all. Correct me if I'm wrong @ctrueden.

**Comment by ctrueden** [comment]
It is planned to add support for both lossy and lossless converters in the `ConvertService`, with API for calling either or both. And currently, the conceit is that conversion must always be lossless.

**Comment by dietzc** [comment]
@Squareys please open a new, dedicated issue for this which doesn't involve `Op`s.
